// See https://aka.ms/new-console-template for more information
Console.ForegroundColor = ConsoleColor.Red;
Console.BackgroundColor = ConsoleColor.White;
Console.Write("                   ^^");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("               ^^   ");
Console.Write("                  ^^^^");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("             ^^^^  ");
Console.Write("                 ^^^^^^");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("           ^^^^^^   ");
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("                ^^^^^^^^");
Console.WriteLine("         ^^^^^^^^   ");
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine("               /        \\       /         \\ ");
Console.WriteLine("              /          \\     /           \\ ");
Console.WriteLine("             /            \\   /             \\ ");
Console.WriteLine("            (               --               ) ");
Console.WriteLine("             \\        |||           |||     / ");
Console.WriteLine("              \\      |||||         ||||    / ");
Console.WriteLine("               \\                          / ");
Console.WriteLine("                \\                        / ");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("                 \\    {            }    / ");
Console.WriteLine("                  \\    {          }    / ");
Console.WriteLine("                   \\     {       }    / ");
Console.WriteLine("                    \\      {    }    / ");
Console.WriteLine("                     \\       {}     / ");
Console.WriteLine("                      \\            / ");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("                       \\          / ");
Console.WriteLine("                        \\        / ");
Console.WriteLine("                         \\      / ");
Console.WriteLine("                          \\    / ");
Console.WriteLine("                           \\  / ");
Console.WriteLine("                            --");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("\n");